name: Build SquirrelsNest.Pecan (develop)

on:
  workflow_dispatch:
  push:
    branches: 
      - develop

env:
  BUILD_PATH: './SquirrelsNest.Pecan'

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: '${{ env.BUILD_PATH }}'

    steps:
      - name: Checkout source
        uses: actions/checkout@v3
      
      - name: Setup .NET Core
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '7.0.102'
          
      - name: Install dependencies
        run: dotnet restore
        
      - name: Build
        run: dotnet build --configuration Release --no-restore
        
      - name: Publish Build
        run: dotnet publish --configuration Release --no-restore --output ./publish
